# Generated by Django 6.0.5 on 2026-06-01 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, limit_choices_to={'rol': 'administrativo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('motivo', models.CharField(choices=[('tramite', 'Trámite'), ('consulta', 'Consulta'), ('documento', 'Documento')], max_length=20)),
                ('estado', models.CharField(choices=[('espera', 'En Espera'), ('llamado', 'Llamado'), ('en_atencion', 'En Atención'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='espera', max_length=20)),
                ('hora_solicitud', models.DateTimeField(auto_now_add=True)),
                ('hora_inicio_atencion', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_atencion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
                ('ventanilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.ventanilla')),
            ],
            options={
                'ordering': ['hora_solicitud'],
            },
        ),
    ]
