# Generated by Django 6.0.5 on 2026-06-01 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('aula', 'Aula'), ('laboratorio', 'Laboratorio'), ('oficina', 'Oficina'), ('bloque', 'Bloque'), ('pasillo', 'Pasillo'), ('entrada', 'Entrada')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('bloque', models.CharField(blank=True, max_length=10)),
                ('piso', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConexionEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=1.0)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('bidireccional', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='rutas.espaciofisico')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='rutas.espaciofisico')),
            ],
            options={
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
